# the name of thr workflow
name: java-maven-ci

# the name of GitHub Event that triggers the workflow
on: 
# triggers the workflow on push/pull req events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# a workflow run is made up of one or more jobs (that can run sequentially or in parallel
jobs:
  # this workflow contains a signle job called "build"
  build:
    # the type of virtual host machine to run the job on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of this job
    steps:
          # selects an action to run as part of a step in your job
          - uses: actions/checkout@v3
          
         # runs a single command using the runners shell
          - name: Run a one-line script    # name to diplay on GitHub
            run: echo Hello, world!

         # runs a set of command using the runners shell
          - name: Run a mulit-line script    # name to diplay on GitHub
            run: 
              echo Add other actions to build, 
              echo test, and deploy your project.

          
  

    
